---
- name: install zabbix-agent
  apt: update_cache=yes name=zabbix-agent state=latest

- name: Start Zabbix agent service
  service: name=zabbix-agent state=started enabled=yes
  ignore_errors: yes

- name: configure zabbix-agent
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="{{ item.var }}=" line="{{ item.var }}={{ item.value }}"
  with_items:
    - { var: "Server", value: "{{zabbix_agent_server}}"}
    - { var: "ServerActive", value: "{{zabbix_agent_server}}:{{zabbix_agent_server_port}}"}
    - { var: "Hostname", value: "{{ansible_hostname}}"}
    - { var: "RefreshActiveChecks", value: "60"}
  notify: restart zabbix-agent
