---
- name: Ensure group "devops" exists
  group:
    name: devops
    state: present

- name: Allow "devops" group to have passwordless sudo
  blockinfile:
    dest: /etc/sudoers.d/devops
    create: yes
    block: |
      %devops ALL=(ALL)  NOPASSWD: ALL

- name: Add the user "devops" with a specific uid, password and group
  user:
    name: devops
    uid: 2001
    group: devops
    home: /home/devops
    password: "$1$7Q5ylRjB$8qx1oKobnhwSjmQqcyVEV1"

- name: Add new SSH Public Key for "devops"
  authorized_key:
    user: devops
    key: "{{ item }}"
    state: present
    exclusive: True
  ignore_errors: True
  with_file:
    - "~/.ssh/google_compute_engine.pub"

- name: apt update & upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: install ncdu
  apt: update_cache=yes name=ncdu state=latest

- name: install vim
  apt: name=vim update_cache=yes state=latest

- name: install nano
  apt: name=nano update_cache=yes state=latest

- name: install mc
  apt: name=mc update_cache=yes state=latest

#    - name: OS
#      debug: msg={{ ansible_distribution }}

#    - name: CPU
#      debug: msg={{ ansible_processor, ansible_processor_cores, ansible_processor_count }}

#    - name: NIC conf, ISP cloud name, HW
#      debug: msg={{ ansible_system_vendor, ansible_product_name, ansible_default_ipv4 }}
