---
- name: Install tomcat8 and tomcat8-admin
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['tomcat8', 'tomcat8-admin']

- name: Start tomcat8 service
  service: name={{ item }} state=started enabled=yes
  loop: ['tomcat8', 'tomcat8-admin']
  ignore_errors: yes

- name: configure tomcat8 users
  lineinfile: dest=/etc/tomcat8/tomcat-users.xml regexp="{{ item.var }}=" line="{{ item.var }}={{ item.value }}"
  with_items:
    - { var: "Server", value: "{{zabbix_agent_server}}"}
    - { var: "ServerActive", value: "{{zabbix_agent_server}}:{{zabbix_agent_server_port}}"}
    - { var: "Hostname", value: "{{ansible_hostname}}"}
    - { var: "RefreshActiveChecks", value: "60"}

- name: configure tomcat8 
  lineinfile: dest=/etc/tomcat8/tomcat-users.xml regexp="{{ item.var }}=" line="{{ item.var }}={{ item.value }}"
  with_items:
    - { var: "Server", value: "{{zabbix_agent_server}}"}
    - { var: "ServerActive", value: "{{zabbix_agent_server}}:{{zabbix_agent_server_port}}"}
    - { var: "Hostname", value: "{{ansible_hostname}}"}
    - { var: "RefreshActiveChecks", value: "60"}
  notify: restart tomcat8
