---
- hosts: all
  become: true
  vars:
    ssh_pubkey_student: "{{ lookup('file', './35500/roles/common/files//rbelyaev.pub') }}"
    student_pass_hash: $1$zQmv.xL1$gb2QsHyL5cSpZtGy81.1G1

  tasks:
    - name: Ensure group "lineate" exists
      group:
        name: lineate
        state: present

    - name: Allow 'lineate' group to have passwordless sudo
      blockinfile:
        dest: /etc/sudoers.d/lineate
        create: yes
        block: |
          %lineate ALL=(ALL)  NOPASSWD: ALL
